### ISSUE TITLE
Had an issue this morning, uninstalled, can't get built in audio to work

### ISSUE THREAD

**Issue by simondsmason** [kyleneideck/BackgroundMusic#100]
This morning Background Music stopped working for me.  I could see the icon flash on the menu bar and then disappear each time.  I couldn't figure out what was happening so I decided to uninstall.  I ran the script and I can connect to my bluetooth speakers fine.  However, if I disconnect my bluetooth speakers then I have no other sound devices.  My built in audio is gone.  I tried reinstall Sierra but that did nothing.  Can someone give me some pointers to get my internal audio working again so I can get the system back to working condition then begin an investigation into what was going on with Background Music?  Thanks.

**Comment by kyleneideck** [comment]
Did you update Background Music or anything like that before it started crashing, or did it just start out of nowhere?

Can you find any relevant crash logs (not just for Background Music) or see any relevant log messages in Console.app? Try filtering on `Process: coreaudiod` in Console.app.

You should be able to find your crash logs in Console.app, but you might want to check for them in `~/Library/Logs/DiagnosticReports` and `/Library/Logs/DiagnosticReports` as well.

I'm pretty sure Background Music will crash on start up if your system doesn't have any audio devices, so maybe your built-in audio device stopped working for some reason. It could be a hardware problem. What output do you get from `ioreg -r -c AppleHDAController`? If you don't get anything from that, try searching the output of `ioreg` for "Audio".

To try to rule out a hardware problem, you could boot into a different OS (using a Linux live USB/CD or whatever) and see if it's able to use your built-in audio device.

**Comment by simondsmason** [comment]
Wow - I didn't even think about a hardware issue.  Good call.  Indeed the internal speakers were not showing up and it appears to have nothing to do with background music.  This is a new MacBook Pro and I have been having issues with it - mostly video related so far.  I had to reboot using the power key this morning and also had my system freeze and the dock reload this morning.  After the system reboot with the power key the internal speakers miraculously appeared.  So I am not sure what is going on yet but I will keep an eye on it.
