### ISSUE TITLE
Better support for volume-less audio devices

### ISSUE THREAD

**Issue by timothybasanov** [kyleneideck/BackgroundMusic#101]
Some of my USB audio devices have volume control disabled: when I try to change volume macOS shows overlay showing that it's not possible.

What is happening: When I route audio through BGA macOS allows me to "change" volume with volume control buttons. It does not affect the actual sound volume though.
What I expect: BGA does not allow to change volume when target device does not support it.

**Comment by kyleneideck** [comment]
This ended up being a way bigger change than I expected so let me know if you find any problems with it. It's tested fairly well, but I don't have any real hardware without volume and mute controls so I just used an aggregate device. Thanks for the report.
