### ISSUE TITLE
Output Device Still Present

### ISSUE THREAD

**Issue by alyh47** [kyleneideck/BackgroundMusic#110]
I uninstalled the Background Music App by moving it from the Applications folder in Finder to Trash, but not the Background Music Device is still listed as an output device in the volume menu, and I do not know how to delete it.

<img width="351" alt="screen shot 2017-04-19 at 1 10 03 am" src="https://cloud.githubusercontent.com/assets/27759528/25165600/efb79118-249c-11e7-8c4d-740b5d36a2da.png">

**Comment by kyleneideck** [comment]
As far as I know, there's no way to automatically remove the virtual device when Background Music.app gets moved to the trash, so you have to run [uninstall.sh](https://github.com/kyleneideck/BackgroundMusic/blob/master/uninstall.sh) (from the terminal) to uninstall everything. 

I believe you should be able to just download an run uninstall.sh on its own, if that's easier.
