### ISSUE TITLE
Route headphones's sound without unplugg them

### ISSUE THREAD

**Issue by sebolito** [kyleneideck/BackgroundMusic#121]
It is possible to leave plugged headphones and only route out sound to desktop internal speakers?

**Comment by kyleneideck** [comment]
I don't think this is possible with the Built-In Audio device that MacBooks have. When you plug headphones in the "Internal Speakers" data source goes away and gets replaced by one called "Headphones". There doesn't seem to be a way to change it.

This thread is pretty old but I think it confirms that's the case for most Apple hardware: https://lists.apple.com/archives/coreaudio-api/2008/Feb/msg00097.html.

Apparently Mac Pros might be an exception, but I don't have access to one to test with. Feel free to reopen this issue if you do, or if any new information comes up.
