### ISSUE TITLE
Doesn't see apps that run in the menu bar

### ISSUE THREAD

**Issue by krp312** [kyleneideck/BackgroundMusic#122]
I have a timer app called "Be Focused Pro" that only runs in the menu bar. I'd love to adjust its volume using your app, but BackgroundMusic doesn't see it.

**Comment by kyleneideck** [comment]
You should be able to find it in the "More Apps" submenu now. I haven't actually tested it with Be Focused Pro, so let me know if it doesn't work for you and I'll reopen this issue.

**Comment by krp312** [comment]
Thank you!!!
