### ISSUE TITLE
Quicklook Volume

### ISSUE THREAD

**Issue by supersaiyansubtlety** [kyleneideck/BackgroundMusic#124]
I would like to be able to control quicklook volume. I've tried adjusting Finder's volume in BM, as that was the only thing I thought it might be tied to. This would be useful when looking through videos with quicklook to find the one you're looking for or organizing videos.

**Comment by kyleneideck** [comment]
I'm pretty sure this was working when I fixed #45, so I guess Apple must have changed the process Finder uses for audio in Quicklook (or its bundle ID). Should be fixed until they change it again. Thanks for the report.
