### ISSUE TITLE
"App Volumes" sliders do nothing in macOS High Sierra

### ISSUE THREAD

**Issue by telnet23** [kyleneideck/BackgroundMusic#134]
In macOS High Sierra, adjusting the "App Volumes" sliders does not change the volume of any applications.

**Comment by kyleneideck** [comment]
I've upgraded to High Sierra (10.13.1 17B48) but App Volumes seems to be working normally for me. I tested it with iTunes and VLC.

What apps have you tried it with? Some don't work yet because of #42. Also, what version of Background Music are you using?

**Comment by telnet23** [comment]
You're right; after experimenting with all of the applications listed in Background Music, I think the issue is indeed related to #42. Adjusting the sliders successfully changes the volume of Google Chrome, iTunes, QuickTime Player, and VLC. However, adjusting the sliders does not change the volume of FaceTime, Finder, Mail, Messages, Safari, and Terminal.

I'm using Background Music version 0.1.1.

I'm going to close the issue since I don't believe it is related to running macOS High Sierra.
