### ISSUE TITLE
Failure during install

### ISSUE THREAD

**Issue by GordLacey** [kyleneideck/BackgroundMusic#135]
I've encountered the same error while installing through Terminal from source, or downloading and trying to install from the files on my computer:

Error details:
Line 228. The last command was (probably)
    LAST_COMMAND="${BASH_COMMAND}" LAST_COMMAND_EXIT_STATUS=$?
which exited with status 0.
[build_and_install.log](https://github.com/kyleneideck/BackgroundMusic/files/1545835/build_and_install.log)

**Comment by kyleneideck** [comment]
It looks like this is the part that failed:

>Error Domain=NSCocoaErrorDomain Code=513 "“PublicUtility.build” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/var/root/Library/Developer/Xcode/DerivedData/BGM-dudxitnygheogygmoeoxhinwpepo/Build/Intermediates.noindex/BGMDriver.build/Release/PublicUtility.build, NSUserStringVariant=(
>    Remove
>), NSUnderlyingError=0x7fe3c627dfc0 {Error Domain=NSPOSIXErrorDomain Code=66 "Directory not empty"}}
>Command builtin-rm failed with exit code 513

Can you try deleting `/var/root/Library/Developer/Xcode/DerivedData/BGM-dudxitnygheogygmoeoxhinwpepo` and installing again?

**Comment by GordLacey** [comment]
Looks like I don't have access to the /var/root folder.

**Comment by kyleneideck** [comment]
What error do you get when you do `sudo rm -r /var/root/Library/Developer/Xcode/DerivedData/BGM-dudxitnygheogygmoeoxhinwpepo`?

In System Preferences > Users and Groups, does it say "Admin" next to your username?

**Comment by GordLacey** [comment]
Yup, I have admin beside my name. Running that command produced no error message.

Running the install command from the local files produced no errors, and the install went through just fine. Thanks for the help!
