### ISSUE TITLE
Messenger.app (high sierra)

### ISSUE THREAD

**Issue by Cooller13** [kyleneideck/BackgroundMusic#138]
HI, I did download this https://fbmacmessenger.rsms.me/ and seems it's not working... already tried trial of SoundControl.app and failed with same result... obviously it's clear that I want soften my sound notification but only in this app specifically... any advice? Thanks

**Comment by kyleneideck** [comment]
Messenger for Mac seems to play `NSUserNotificationDefaultSoundName` for sound notifications: https://github.com/rsms/fb-mac-messenger/blob/0207c110ce1f97d1b1dcf68284173113f0487154/Messenger/JSNotification.js.mm. So I'd expect that the sound would actually be played by `systemsoundserverd` as a "system sound".

If you install the [latest snapshot version of Background Music](https://github.com/kyleneideck/BackgroundMusic/releases/download/0.2.0-SNAPSHOT-e83d07f/BackgroundMusic-0.2.0-SNAPSHOT-e83d07f.pkg), you can control the volume of system sounds. Unfortunately there's no way to tell that Messenger for Mac was the app that told `systemsoundserverd` to play the notification sound, so there's no way to change the volume of systems sounds from Messenger for Mac without also changing the volume of other system sounds.

Alternatively, Messenger for Mac is open source, so you could probably just change the line `notif.soundName = NSUserNotificationDefaultSoundName;` to `notif.soundName = nullptr;` in the file I linked above to stop it playing the notification.

**Comment by Cooller13** [comment]
thanks 👍
