### ISSUE TITLE
Cracking sound after switching to headphones and making phone / FaceTime calls

### ISSUE THREAD

**Issue by setu4993** [kyleneideck/BackgroundMusic#166]
Version: 0.2.0 (built by pulling from Git, so probably snapshot)
OS: macOS Mojave 10.14

I use Bluetooth headphones for making and receiving phone (and FaceTime) calls. Every time I connect to the headphones and am making the call, I hear a cracking sound instead of the normal waiting-to-answer ringer. This happens only when running BackgroundMusic.

Secondly, not sure if this is intended, increasing volume from the default 50% to above makes it start to crack. If it is intended, it should be added to the documentation.

**Comment by fishg** [comment]
I face the problem like you:
1. set BackgroundMusic as default record device
2. play a music in any player
3. open BackgroundMusic app
4. open VoiceMemos.app and start record

then will heart music and noise obviously.

**Comment by setu4993** [comment]
I am running the most recent Snapshot build with Mojave 10.14.1 and this issue seems to be resolved.
