### ISSUE TITLE
Memory leak on 10.14.1 beta

### ISSUE THREAD

**Issue by jandreaucodes** [kyleneideck/BackgroundMusic#168]
I've been running 10.14.1 for a few weeks and notice that almost daily Background Music eats up about 10 gigs of RAM on my machine.

I force quit it and restart it and it's fine for a day or two, then back up to 10 gigs.

This didn't happen on 10.14, so I think it'll resolve itself once 10.14.1 is out of beta, but wanted to bring it up, just in case.

**Comment by kyleneideck** [comment]
I upgraded to 10.14.1 Beta (18B67a) yesterday and kept Background Music running overnight with audio playing, but I'm not seeing much memory being leaked, if any.

I also tried checking for leaks with Instruments. If I'm reading its output right, some frameworks/libraries leaked a small amount, but BGMApp itself didn't leak any memory while I was profiling it.

Do you think I might just need to wait longer?

The next time it happens you could try `heap -s -guessNonObjects 'Background Music'` and `leaks 'Background Music'` to see if they tell you anything useful.

**Comment by jandreaucodes** [comment]
Not seeing the issue in the latest build, so perhaps Apple fixed whatever was causing it. Probably something in coreaudiod
