### ISSUE TITLE
Upgrade in Homebrew cask

### ISSUE THREAD

**Issue by zjzsliyang** [kyleneideck/BackgroundMusic#172]
Thanks for this fantastic app.
However, when I install through brew cask, the version is 0.1.1. Would you mind upgrading this?

**Comment by kud** [comment]
https://github.com/Homebrew/homebrew-cask/pull/55413 :)

**Comment by kud** [comment]
It's now merged. Enjoy!

**Comment by kyleneideck** [comment]
That's great. Thanks, @kud.
