### ISSUE TITLE
Move "output device" to a more direct path

### ISSUE THREAD

**Issue by kud** [kyleneideck/BackgroundMusic#175]
Hey,

As I often change my output device, it could be great to have this select in a more global select.

For the moment, it's BackgroundMusic icon > Preferences -> Output Device

It could be great to have sometimes like a section of BackgroundMusic like we already have "Volumes".

It could be:

## Volumes

- ....
- ...

## Output Devices

- ...
- ...

**Comment by kyleneideck** [comment]
I actually think I just made this change a few weeks ago for #170. It looks like this in the latest snapshot builds:

<img width="278" alt="capture d ecran 2018-11-27 a 1 10 28 pm" src="https://user-images.githubusercontent.com/2290968/49053869-10e6e500-f246-11e8-8a58-332d824ded46.png">

Is that what you had in mind?

**Comment by kud** [comment]
Oh that's amazing. Perfect, thank you.

I'm still on the 0.2.0. :)
