### ISSUE TITLE
Icon: show volume

### ISSUE THREAD

**Issue by kud** [kyleneideck/BackgroundMusic#183]
To be fair, I'd like to remove the default volume icon from the bar, to only have the one of this application. However, I like to see the volume in the bar so I can't remove the default one yet.

**Comment by kyleneideck** [comment]
Done, thanks for the suggestion. I couldn't think of a nice way to show the volume on the current icon, so I just added an option to copy the default volume icon. Does that make sense?

**Comment by kud** [comment]
Yes :)
