### ISSUE TITLE
BGMXPCHelper manual build/install fails if source checkout dir has spaces

### ISSUE THREAD

**Issue by HofiOne** [kyleneideck/BackgroundMusic#187]
Installation phase will fail if source checkout dir name has any space, like "Background Music" 

/bin/sh -c /Users/hofi/Develop/Others/Background\\\ Music/BGMApp/build/BGMApp.build/Release/BGMXPCHelper.build/Script-276972891CAFCE91007A2F7C.sh
/bin/bash: /Users/hofi/Develop/Others/Background: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

** INSTALL FAILED **

**Comment by HofiOne** [comment]
Dirs without spaces work fine.

**Comment by kyleneideck** [comment]
Fixed, thanks!
