### ISSUE TITLE
background-music-pre: Brew does not have a cask with this name

### ISSUE THREAD

**Issue by carstenhag** [kyleneideck/BackgroundMusic#195]
```
brew cask install background-music-pre
Error: Cask 'background-music-pre' is unavailable: No Cask with this name exists.
```

I updated brew before running it, so not sure why this happens.

Homebrew 2.0.2
Homebrew/homebrew-core (git revision 46be2; last commit 2019-02-27)
Homebrew/homebrew-cask (git revision 69db7; last commit 2019-02-27)

**Comment by kyleneideck** [comment]
It looks like you probably need to run `brew tap homebrew/cask-versions` first. I've added it to the README (14df80da2436e716eaa840c9a8e534bee20e3b2e). Thanks for reporting it.

**Comment by carstenhag** [comment]
Thanks! Works!
