### ISSUE TITLE
how to set auto login from this program?

### ISSUE THREAD

**Issue by Macfa** [kyleneideck/BackgroundMusic#199]
Hi,
I have been using this program closely

but, I have a little issue,
It's a .. automatic login
I can't find an automatic login button when I turn the computer on

how to set auto login from this program?

**Comment by kyleneideck** [comment]
We haven't added a menu option for that yet, but you should be able to add Background Music to your login items by following <https://support.apple.com/kb/ph25590?locale=en_AU>.

**Comment by Macfa** [comment]
@kyleneideck 
thanks I got problem
