### ISSUE TITLE
Uninstall Issues

### ISSUE THREAD

**Issue by m-szczepanik** [kyleneideck/BackgroundMusic#214]
I tried to uninstall the program. I have removed applications from the Finder / App, but when I enter the speaker settings I still have the program shown and it annoys me.
What can I do?

<img width="248" alt="Zrzut ekranu 2019-06-15 o 02 32 11" src="https://user-images.githubusercontent.com/51707009/59544815-dc065b00-8f15-11e9-9570-50515140066c.png">

**Comment by kyleneideck** [comment]
I've been meaning to put an uninstall button in the app, but I haven't gotten around to it yet, so there's just an uninstall script in the app bundle: https://github.com/kyleneideck/BackgroundMusic#uninstall.

But since you've deleted it already, it might even be quicker to follow the manual uninstall instructions: https://github.com/kyleneideck/BackgroundMusic/blob/master/MANUAL-UNINSTALL.md.

**Comment by m-szczepanik** [comment]
> I've been meaning to put an uninstall button in the app, but I haven't gotten around to it yet, so there's just an uninstall script in the app bundle: https://github.com/kyleneideck/BackgroundMusic#uninstall.
> 
> But since you've deleted it already, it might even be quicker to follow the manual uninstall instructions: https://github.com/kyleneideck/BackgroundMusic/blob/master/MANUAL-UNINSTALL.md.


These methods do not work. I tried them before giving your instructions, I am thinking about reinstalling the system.

**Comment by m-szczepanik** [comment]
> I've been meaning to put an uninstall button in the app, but I haven't gotten around to it yet, so there's just an uninstall script in the app bundle: https://github.com/kyleneideck/BackgroundMusic#uninstall.
> 
> But since you've deleted it already, it might even be quicker to follow the manual uninstall instructions: https://github.com/kyleneideck/BackgroundMusic/blob/master/MANUAL-UNINSTALL.md.

Ok, I did a little bit around. I downloaded the installer, installed it, then downloaded the program files to the Desktop, then I went to it using the console and ran uninstall.sh :). Maybe it will be a solution for others.
