### ISSUE TITLE
Firefox slider has no effect as audio is being played from per-tab processes

### ISSUE THREAD

**Issue by Zegnat** [kyleneideck/BackgroundMusic#215]
This is probably the exact same issue as #197, except the same behaviour can be noticed in my version of Firefox Nightly. If you’d want to track this as one issue, feel free to close and update #197.

Audio is output from tabs in Firefox by their separate background processes. Sliding the main Firefox Nightly audio slider has no effect, instead you have to dig down under More Apps to find the correct tab process. As all these processes have the same name, there is no guidance to help here.

It would be nice if:

1. The main Firefox Nightly slider would also affect all the subprocesses at once (except if a subprocess already has a custom value), and
2. subprocesses could display some hints to help find the correct one.

I am guessing it is impossible to get tab names or whatever from a separated ”Web Content” process. But maybe BackgroundMusic could display a little icon if the process is known to have sound output at all? This could be applied to all process icons to more easily find ones responsible for sound.

![Screenshot: showing expanded “More Apps” menu with several “Firefox NightlyCP Web Content” items.](https://user-images.githubusercontent.com/490579/59963256-d51cb100-94f0-11e9-868c-af47ad3c2579.png)

**Comment by kyleneideck** [comment]
Are you still able to reproduce this? I just tried in Firefox and Firefox Nightly on macOS 10.14, but the main volume slider always worked for me.

It currently associates the main volume slider to the subprocesses with a hardcoded map from the bundle IDs apps use for audio to the bundle IDs of their subprocesses, which includes mappings for Firefox and Firefox Nightly. What version of Background Music are you using? If it's an older version, it might not have the right bundle IDs for Firefox.

**Comment by Zegnat** [comment]
Firefox Nightly seems to work fine with the main volume slider now. Though I only tested quickly with a single YouTube video. This issue was originally opened for BackgroundMusic 2.0 though, so who knows which exact update (of either Firefox or BGM) has fixed it.

Closing either way.
