### ISSUE TITLE
Catalina Music app autopause request

### ISSUE THREAD

**Issue by theLMGN** [kyleneideck/BackgroundMusic#216]
I'm not sure how you're currently controlling it, [but my app (which uses AppleScript) it's a simple replace "iTunes" with "Music"](https://github.com/theLMGN/tuneCord/commit/462646040b0b1178969b4b95a17711ae57285f73) as the two apps are basically the same codebase

**Comment by theLMGN** [comment]
Also, sidenote: on my Macbook which is running a HiDPI screen, and two regular screens, this happened with the icon on both screens
![image](https://user-images.githubusercontent.com/12257112/59977941-28fdc780-95cf-11e9-8db6-2dc485081e87.png)

**Comment by formadi** [comment]
If you want to use Auto Pause in Catalina's Music app at the current source, change the source code below

BGMApp/BGMApp/Music Players/BGMiTunes.m

`
    if ((self = [super initWithMusicPlayerID:[BGMiTunes sharedMusicPlayerID]
                                        name:@"Music"
                                    bundleID:@"com.apple.Music"])) {
        scriptingBridge = [[BGMScriptingBridge alloc] initWithMusicPlayer:self];
    }
    
    return self;
}`
