### ISSUE TITLE
Troubles with slack

### ISSUE THREAD

**Issue by kud** [kyleneideck/BackgroundMusic#224]
When I use video call on slack, if background music is the source, the sound doesn't work well.

I've got to switch to the right input/output in macOS directly, instead of BGM.

Any idea why?

**Comment by gchilds** [comment]
What do you mean by “BGM is the source” and how does the sound that isn’t working well sound?

On which end of the slack call is the sound bad? 

What are you trying to do?

**Comment by kud** [comment]
1/ 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/655838/61533798-29527c80-aa2e-11e9-920b-45a46404f3ef.png">

2/ the sound is jerky/irregular

3/ 
<img width="39" alt="image" src="https://user-images.githubusercontent.com/655838/61533852-4a1ad200-aa2e-11e9-94ea-5442122da6f1.png"> This on slack.

**Comment by kud** [comment]
Still relevant.

If you use background music as source, slack audio is broken.

**Comment by kud** [comment]
Seems to be fixed now. Thanks. :)
