### ISSUE TITLE
Auto-pause support Google Play Music Desktop Player

### ISSUE THREAD

**Issue by hieu-nn** [kyleneideck/BackgroundMusic#229]
Hello, can you please add support to Google Play Music Desktop Player: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

Thank you for a very useful tool!

**Comment by bryancasler** [comment]
Came to ask for the same thing. Do all my listening through the app.

**Comment by kyleneideck** [comment]
I actually added GPMDP recently, it just didn't show up in the changelog because the SNAPSHOT build failed. But the one after that worked, so you should just need to update to https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.3.0-SNAPSHOT-04f1730.
