### ISSUE TITLE
Amazon Music App

### ISSUE THREAD

**Issue by HTS126** [kyleneideck/BackgroundMusic#236]
Hi

Could you please add support for the Amazon Prime Music app found here: 
https://www.amazon.co.uk/b?ie=UTF8&node=14074016031

Thanks

**Comment by Yann-R** [comment]
Hi,
It seems that `Amazon Music` is correctly supported now? And this issue could be closed?

In other words, `Background Music` can adjust the volume of this music player application for desktop downloaded from https://www.amazon.com/b?ie=UTF8&node=2658409011
is it the same for you?

Concerning the support of auto-pause for Amazon Music, it's  https://github.com/kyleneideck/BackgroundMusic/issues/90
Regards.
