### ISSUE TITLE
BGM Driver not loaded on Catalina 10.15 b7 until reboot 

### ISSUE THREAD

**Issue by gchilds** [kyleneideck/BackgroundMusic#241]
Killing `coreaudiod` doesn't seem to be enough to get `/Library/Audio/Plug-Ins/HAL` drivers to be noticed anymore. (trivia: `/Library/Audio/Plug-Ins/HAL` doesn't even exist in a fresh Catalina install).

The converse happens for uninstalling too, so even though the .driver package is gone, the device is still available.

Killing other processes, like `com.apple.audio.SandboxHelper` and `com.apple.audio.DriverHelper` doesn't help either.

p.s. I haven't tested whether the driver state is updated by logging out and in or waiting for `n` hours.

**Update**
Logging out and in does not help.

**Comment by gchilds** [comment]
It looks like `coreaudiod` is catching `SIGTERM` and _not_ exiting, so using `SIGKILL` fixes the problem:

`killall -9 coreaudiod`.

I think I'll log the `SIGTERM` thing with Apple. It should exit.

**Comment by kyleneideck** [comment]
Thanks for figuring all of this out. I think I actually found a fix for this -- just through luck, before you figured out what was actually causing the problem -- a few weeks ago but didn't push the commit for some reason. I just pushed it now: e6e784b013602446db193232a1f9fe85c147cfbf

This is the command that works for me with SIP enabled: `sudo launchctl kickstart -k system/com.apple.audio.coreaudiod`

```
$ csrutil status
System Integrity Protection status: enabled.
$ pgrep coreaudiod
1504
$ sudo launchctl kickstart -k system/com.apple.audio.coreaudiod
$ pgrep coreaudiod
1588
```

**Comment by gchilds** [comment]
ok, thanks - it's nice to have an alternative.
