### ISSUE TITLE
Confusion regarding the "Allow BackgroundMusic to access your Microphone" permission when installing on Catalina

### ISSUE THREAD

**Issue by danmattera** [kyleneideck/BackgroundMusic#257]
I installed the app today for the first time (Catalina 10.15.1, BM 0.3.2) and declined the permission prompt to allow BM to access my Microphone because I only plan to use BM for controlling output-related audio and don't like handing out needless permissions to things. 

As I began playing around with things I found that the per-app volume controls did not work. The only thing that did was adjusting the volume of which ever output device was selected.

Additionally, I followed the suggestion from another issue and confirmed that BM was not being automatically changed to the output device in System Preferences. If I did so manually, all audio ceased, regardless of any volume settings.

I went back and granted the Microphone permission to BM in System Preferences and restarted the app and then everything began working as expected; BM was being set automatically as the output device, audio was playing, and the per-app volume settings being honored.

With that, I was hoping to get some clarification as why this permission is necessary for BM to function and perhaps see about the possibility of that changing in future releases?

**Comment by gchilds** [comment]
Needing microphone access is a macOS permissions/privacy design bug - as BGM doesn't use any microphones. 

However maybe there's a case for yet another macOS privacy prompt as you can set up BGM to record app audio output (screen recording has a prompt), but macOS currently has no way to know that that's what's BGM is doing. 

A BGM that doesn't need the microphone access prompt has come up before: https://github.com/kyleneideck/BackgroundMusic/issues/177

and there the author hypothesises an alternative solution, but I think the current design is the most possible, cleanest and most supported one possible right now.

**Comment by danmattera** [comment]
Gotcha, thanks @gchilds I didn't see that existing issue when I went looking earlier. 

I pretty much assumed as much though, that this is just poor wording on macOS's end and that the permission it titles "Microphone Access" should techincally be called "Virtual and/or Physical Input Devices"
