### ISSUE TITLE
Need to check my understanding about the product

### ISSUE THREAD

**Issue by hemangshah** [kyleneideck/BackgroundMusic#286]
My understanding with this app is that, let's say we've two apps, A1 and A2, both are capable to play sound (consider a streaming service), now I set the output device to Background Music and tried setting A1 volume to 0 and setting A2 volume to full but none of them is working as per the expectations, I thought while I want to keep listen to the sound from A2, A1 will continue and I should not hear the volume from it. Is this the correct understanding? If yes, for some reason I'm not getting this behaviour here. I can share more information on request.

**Comment by kyleneideck** [comment]
Your understanding sounds correct to me. If you turn the volume back up for A1, does the audio from A2 become audible as well?

**Comment by hemangshah** [comment]
Thanks for the quick response, so in my case here, I have set volume of A1 to 0 and A2 to full.
But still I can hear the sound from A1 and A2 both at the same time. Changing the volume as per your suggestion doesn't help.

**Comment by hemangshah** [comment]
A1 is Microsoft Teams app - Set to 0.
A2 is Udemy Website - Set to full volume.
Still listening sound from both the apps.

**Comment by kyleneideck** [comment]
You might need to look in the More Apps menu for Microsoft Teams. Instructions here:

https://github.com/kyleneideck/BackgroundMusic/issues/268#issuecomment-604977210

**Comment by hemangshah** [comment]
Setting as per the suggestions also doesn't help.

**Comment by hemangshah** [comment]
Fixed as per the comment in another thread. Thanks again.
