### ISSUE TITLE
please add Zoom meeting

### ISSUE THREAD

**Issue by ankur-chaudhary** [kyleneideck/BackgroundMusic#288]
hi team, thanks for this application, please add Zoom meeting application sound control.

**Comment by kyleneideck** [comment]
Have you seen https://github.com/kyleneideck/BackgroundMusic/issues/283?

**Comment by ankur-chaudhary** [comment]
hi Kyle, yes Background music is in selected state, controls for other apps like Bluejeans, Firefox, Chrome are working for Zoom its still not working.

**Comment by kyleneideck** [comment]
@ankur-chaudhary Can you post a screenshot of your audio settings in Zoom? I just tested it and it worked for me.

If you're not using it already, it might be worth trying with the latest snapshot build to see if that makes any difference: https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-f24a6cb

**Comment by ankur-chaudhary** [comment]
My bad, its working now. i did not change settings within Zoom, i just changed master speaker only, but didn't change the Zoom speaker to BackgroundMusic.

Thanks Kyle for wonderful application!!
