### ISSUE TITLE
Can't set audio on Chrome Catalina 10.15.4

### ISSUE THREAD

**Issue by cenzowm** [kyleneideck/BackgroundMusic#289]
Someone can help me?

**Comment by cenzowm** [comment]
Btw it's correct this setting?
<img width="862" alt="Schermata 2020-04-23 alle 11 03 40" src="https://user-images.githubusercontent.com/19749702/80080630-2bfc7800-8552-11ea-99d0-f0863b910491.png">

**Comment by MarioZarate** [comment]
I installed this version and work good for me.
https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-f24a6cb

**Comment by cenzowm** [comment]
> I installed this version and work good for me.
> https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-f24a6cb

Thanks bro! It works!

**Comment by kyleneideck** [comment]
Thanks @MarioZarate.

By the way, for anyone else with similar questions, there might be some more info in #61 or #258.

**Comment by levity** [comment]
Installing 0.4.0 also works for me, thanks!
