### ISSUE TITLE
Volume bug and AutoPause with YTMusic app

### ISSUE THREAD

**Issue by noizo** [kyleneideck/BackgroundMusic#309]
Please add Auto Pause support for https://github.com/steve228uk/YouTube-Music

Now volume control is not working for this app.

**Comment by noizo** [comment]
just learned that https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL- is actually can control YT Music. So it not really a big deal to work on this one, since MarshallOfSound GPMDP works much better.

**Comment by RaiserWeb** [comment]
Volume doesn't work for YT Music app, which was the main reason I installed this. Looks like a good tool in general.
