### ISSUE TITLE
Doesn't work with Zoom

### ISSUE THREAD

**Issue by kyleplo** [kyleneideck/BackgroundMusic#313]
I installed this so that I could have zoom open and watch a call while listening to something else, but this program doesn't work with zoom.

Mac Version: Catalina 10.15.4
Zoom Version: 5.0.2
BackgroundMusic Version: Latest stable, installed from DMG

**Comment by kyleneideck** [comment]
We've got a few issues open about Zoom: #159, #283, #267, #223, #288. Can you have a look through and see if any of them help? Usually the problem is that Zoom hasn't configured itself to play audio through the Background Music audio device, so you have to change that setting manually.

**Comment by kyleplo** [comment]
Thanks, that worked.
