### ISSUE TITLE
How do you remove BGM Audio Devices?

### ISSUE THREAD

**Issue by 69420XD** [kyleneideck/BackgroundMusic#354]
![Screenshot 2020-08-18 at 12 07 43](https://user-images.githubusercontent.com/64201549/90506040-91045b00-e14b-11ea-8630-f527b96e7936.png)
![Screenshot 2020-08-18 at 12 07 46](https://user-images.githubusercontent.com/64201549/90506056-92ce1e80-e14b-11ea-8b5f-ad901394df9a.png)

The "-" symbol is greyed out, how do I remove the audio devices since I no longer want them?

**Comment by Kentakoong** [comment]
yeah me too. I wanted it to be removed when I'm not using it anymore

**Comment by kyleneideck** [comment]
@69420XD https://github.com/kyleneideck/BackgroundMusic#uninstall

**Comment by 69420XD** [comment]
> @69420XD https://github.com/kyleneideck/BackgroundMusic#uninstall

It worked, thanks!
