### ISSUE TITLE
Doesn't work with zoom calls

### ISSUE THREAD

**Issue by IvanSobko** [kyleneideck/BackgroundMusic#358]
Changing sound volume for Zoom app doesn't affect anything.

**Comment by lowjac69** [comment]
hey man, there's an easy fix for this. If you go to your audio settings in Zoom, you can set your "speaker" to BackgroundMusic. I was having trouble, and this helped me. Good luck.

**Comment by IvanSobko** [comment]
Wow, thanks man. It really helped :)
