### ISSUE TITLE
Install issue on OS X 10.11.4 (15E65)

### ISSUE THREAD

**Issue by DeveloperZhou** [kyleneideck/BackgroundMusic#36]
I clone the source code and install it. 
But the terminal returns 

```
[latino 12:48 BackgroundMusic]$./build_and_install.sh
Installing the virtual audio device Background Music Device.driver to /Library/Audio/Plug-Ins/HAL.
Password:
ERROR: Install script failed at line 154. This is probably a bug in the script. Feel free to report it.
ERROR: Install script failed at line 62. This is probably a bug in the script. Feel free to report it.
ERROR: Build step failed. See build_and_install.log for details.
Failed command:

[latino 12:48 BackgroundMusic]$more build_and_install.log
Installing the virtual audio device ESC[1mBackground Music Device.driverESC(BESC[m to ESC[1m/Library/Audio/Plug-Ins/HALESC(BESC[m.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Is it a bug? Or I just do something wrong?

**Comment by kyleneideck** [comment]
Do you have Xcode installed? Unfortunately, xcodebuild stopped working without Xcode a few years ago, so you would need to install it to build Background Music. Xcode.app takes up about 9GB, too, so it's probably not worth the hassle just for this. 

I'm working on a binary release, but I want to make it [reproducible](https://reproducible-builds.org/) if possible, or at least not built on my/someone's personal machine. Travis CI should work for that, but I'm still in the middle of trying it.

If you do have Xcode installed, you might just need to use xcode-select to tell xcodebuild where your Xcode.app is. I think the command would be `xcode-select --switch /the/path/to/your/Xcode.app`.

**Comment by DeveloperZhou** [comment]
As you said, I didn't install Xcode because of its `big` size. And I am expecting your binary versions.

Anyway, thanks for your reply and contributions of this good app.
