### ISSUE TITLE
Please add support for these apps 

### ISSUE THREAD

**Issue by ElvisBerger** [kyleneideck/BackgroundMusic#361]
I got this app because I wanted to silence Zoom without having to turn off the sound of my device (you know, for those times meetings get tedious). I soon realized this was not possible (I also read somewhere that it doesn't work for Discord either). It does work pretty well for most of my other apps though and I like it, so I'll definitely keep it. Ah, and the logo looks good. 

Peace

**Comment by kyleneideck** [comment]
Have you tried the recommendations in these issues? #267 #313 #288 #335 #210

**Comment by ElvisBerger** [comment]
That solved the problem, it works great now. Thanks =)
