### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by yifan121461** [kyleneideck/BackgroundMusic#363]
I'm using MacOS 10.14. After I download this app, restart my computer, this app does not work at all. I cannot change volume of individual apps on my laptop like chrome or zoom.

**Comment by kyleneideck** [comment]
I don't remember exactly why, but Chrome doesn't always work yet. I started working on it a while ago, but never got around to finishing it. I think this is the issue for it: #61 

Zoom should work, but you have to change the output device to Background Music in Zoom's preferences: #267 #313 #288 #335
