### ISSUE TITLE
Cannot find Safari in the appbar menu

### ISSUE THREAD

**Issue by mohammadreza490** [kyleneideck/BackgroundMusic#366]
I have Google Chrome and Safari both open but I cannot find Safari in the appbar to manage the sound of it
<img width="710" alt="Screenshot 2020-10-07 at 14 30 16" src="https://user-images.githubusercontent.com/47437328/95337319-a2472980-08a9-11eb-8c4a-3f4ec8691cd2.png">

**Comment by AshH2O** [comment]
Safari would be in More apps section. 
Pro tip - Safari slider doesn't work sometimes. it comes up as com.apple.webkit... You have too check them manually. There might be multiple sliders with this same name as they are for different tabs as safari prevents cross-website tracking by treating each tab as a different window.
Hope this helps :)
