### ISSUE TITLE
Could not find the Background Music virtual audio driver

### ISSUE THREAD

**Issue by GarageMan** [kyleneideck/BackgroundMusic#375]
Hello, dear developers and community.

I ran Background Music successfully on my MacBook Pro (Catalina 10.15.7) over the past month.
Unfortunately, I installed (without reading about known issues) the app eqMac, which lead to a lot of issues.
So, I uninstalled eqMac, removed all garbage.
Background Music did not work any longer.
In uninstalled it (following the given instructions) and re-installed it from the scratch (pkg file).

The installation routine showed "Installation Successful", but a message popped up telling "Could not find the Background Music virtual audio device".
I followed the given instruction to check "Background Music Device.driver" is installed in "/Library/Audio/Plug-Ins/HAL" and restarted coreaudiod "sudo killall coreaudiod".

Unfortunately, all without success. Background Music does not start any more.

Any idea? (I am not a Linux crack, so please be regardful ;-)

.:. lutz

**Comment by kyleneideck** [comment]
Do you see a device called "Background Music" in the Sound pane in System Preferences? If not, `coreaudiod` might not have restarted.

You could try this command: `sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod`. It should do the same thing as `sudo killall coreaudiod`, but I don't think `sudo killall coreaudiod` works on recent versions of macOS anymore. (We should update that error message.) Or if you want to be sure, you could just restart your computer.

If the Background Music device still doesn't show up, try installing the latest snapshot release from [the releases page](https://github.com/kyleneideck/BackgroundMusic/releases).
