### ISSUE TITLE
big sur

### ISSUE THREAD

**Issue by Ankerguy** [kyleneideck/BackgroundMusic#386]
MacOS 11.1 big sur is coming!!!

**Comment by kyleneideck** [comment]
Try this snapshot for now: https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-c0ab98b

We've got a few other issues about Big Sur, so I'm going to close this as a duplicate. Hopefully I'll be able to release a fully working version for Big Sur soon. Subscribe to #328 if you want to be notified about it.
