### ISSUE TITLE
I remove the app manually, my device lost sound. so i have to run uninstall.sh again,but system errors comes. This tool is danger.

### ISSUE THREAD

**Issue by QiuLihua83** [kyleneideck/BackgroundMusic#40]
I remove the app manually, my device lost sound. so i have to run uninstall.sh again,but system errors comes. This tool is danger.

**Comment by kyleneideck** [comment]
Hi, sorry you're having trouble with it. What errors are you getting from uninstall.sh? When you followed the manual uninstallation instructions, did you change your default audio device (in the Sound section of System Preferences) at least once after restarting coreaudiod, and then choose your real audio device as the default? It might also help to look in your system.log. 

And can you check that the coreaudiod process is running on your system? On some systems with older versions of launchctl, uninstall.sh will restart coreaudiod by unloading it and then reloading it, so it's possible that launchctl failed to reload it for some reason. You can try loading coreaudiod yourself with `sudo launchctl load /System/Library/LaunchDaemons/com.apple.audio.coreaudiod.plist`.

If none of that fixes your sound, you might have to restart your computer.

**Comment by Xosmond** [comment]
Please can you tell me whats the name of the extension(output sound device) to erase from my system?. PD: This software made my computer to work very weird with lags.
