### ISSUE TITLE
Doesn't work on Chrome, Zoom, Messenger...

### ISSUE THREAD

**Issue by vincbeaulieu** [kyleneideck/BackgroundMusic#418]
It was working for a while, and it stopped.
I have uninstalled it, then reinstalled it. Restarted the computer...
It started working again! And then stop.

I am running it on Mojave.

**Comment by vincbeaulieu** [comment]
Actually, the software stop working once we install Zoom.

**Comment by vincbeaulieu** [comment]
I've installed the snapshot version, and it worka everywhere except Zoom.

**Comment by LangdalP** [comment]
I have noticed the same problem with Zoom. Whenever I start Zoom, Background Music seems to crash and quit silently.

**Comment by joshfix** [comment]
I use a StarTech docking station for my mac running Catalina. When I use my laptop speakers for audio, it all seems to work with the exception of Zoom. Zoom audio has no effect and comes through loud and clear, but I can adjust the audio for other apps. When I run the audio through my docking station, nothing works.

**Comment by zac-j-harris** [comment]
For zoom if it's simply a lack of usability and not crashing, in Zoom preferences set "speaker" as background music and it will push output through the app.

**Comment by joshfix** [comment]
@zac-j-harris worked like a charm! thank you!

**Comment by vincbeaulieu** [comment]
@zac-j-harris Thanks, it is working now!
