### ISSUE TITLE
Does not work with Microsoft Teams

### ISSUE THREAD

**Issue by MoonPhoenix83** [kyleneideck/BackgroundMusic#441]
**Description of the bug**
The audio works through Microsoft Teams, but the volume cannot be changed. i have tried helpers in the more apps section but still does not work

**Steps to reproduce**
1. Go to Microsoft Teams on MacOS Big Sur 
2. Start new meeting
3. Attempt to change volume through background music

**Versions**
 - Background Music: 0.4.0-SNAPSHOT-c0ab98b
 - macOS: 11.2 Public Beta Big Sur

**Hardware**
 - Computer: MacBook Air (Retina, 13-inch, 2020)
 - Audio Device: Sony WH-XB900N

**Comment by Noloki** [comment]
Instead of trying to change the volume of the teams app itself, try changing the volume of a process called "Microsoft Teams Helper". You can find it in the "more apps" tab.

**Comment by kyleneideck** [comment]
You might also need to go into the settings in Teams and change the output device to "Background Music".

**Comment by MoonPhoenix83** [comment]
Thanks @kyleneideck and @Noloki, I have now fixed the issue
