### ISSUE TITLE
If there is another one support Windows10?

### ISSUE THREAD

**Issue by lyscop** [kyleneideck/BackgroundMusic#443]
Unfortunately, there is no one to support Win10 with Chrome.

**Comment by kyleneideck** [comment]
The closest thing to Background Music on Windows I've heard of is [mute.fm](http://www.mutefm.com/index.html). And of course the built-in volume mixer.

**Comment by lyscop** [comment]
> The closest thing to Background Music on Windows I've heard of is [mute.fm](http://www.mutefm.com/index.html). And of course the built-in volume mixer.

It seems nice, thank you.
