### ISSUE TITLE
Left behind "Background Music" device after uninstall

### ISSUE THREAD

**Issue by singaltanmay** [kyleneideck/BackgroundMusic#447]
Left behind "Background Music" device after uninstall

**Description of the bug**
> I uninstalled the program through Lauchpad and homebrew but still there is a "Background Music" input and output device left behind in System Preferences. It doesn't do anything and is benign but is still annoying. Uninstalling a program should undo all the changes it made to the device.

**Steps to reproduce**
1. Install BackgroundMusic
2. Uninstall BackgroundMusic
3. Go to System Preferences > Sound > Output

**Versions**
> Please complete the following information.
 - Background Music:  "0.3.2"
 - macOS: Catalina 10.15.7

**Comment by kyleneideck** [comment]
https://github.com/kyleneideck/BackgroundMusic/blob/master/MANUAL-UNINSTALL.md

This is pretty common, unfortunately. Let me know if that link doesn't fix the problem for you.

**Comment by singaltanmay** [comment]
Restarting `coreaudiod` fixed it. Thanks!
