### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by ErichthoniusX** [kyleneideck/BackgroundMusic#456]
The installation failed, it says The Installer encountered an error that cased the installation to fail. Contact the software manufacturer for assistance.

Steps to reproduce
1. Install it using the Installer and it will pop up the error message.

Versions**
 - Background Music: "0.4.0-SNAPSHOT-c0ab98b". 
 - macOS: 11.2.1
**Hardware**
 - Computer: 2017 21-inch iMac

**Comment by kyleneideck** [comment]
After you try to install, you should get some logs in `/var/log/install.log`. Can you copy them out of that file and post them here?

Also, check to see if it put `Background Music.app` in `/Applications`. It's unlikely, but the installation could have actually worked and the failure could have been a false positive. I added some retrying code to the installer to help with that: 0e0cc5fd05cf14454137ac09424897a2054546f5. (Haven't released a snapshot build that includes that change yet, though.)

**Comment by denuradhan** [comment]
this is mine
```
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=denuradhan USER=denuradhan USERNAME=denuradhan /usr/sbin/installer -pkg /opt/homebrew/Caskroom/background-music/0.3.2/BackgroundMusic-0.3.2.pkg -target /` exited with 1. Here's the output:
installer: Package name is Background Music 0.3.2
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “BackgroundMusic-0.3.2.pkg”.)

```

**Comment by ljcucc** [comment]
same:
```
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “BackgroundMusic-0.3.2.pkg”.)
```

**Comment by kyleneideck** [comment]
@denuradhan @ljcucc Try the latest SNAPSHOT release or

```
brew tap homebrew/cask-versions
brew install --cask background-music-pre
```

I've been trying to migrate the project from TravisCI to GitHub Actions so I can release a new (non-snapshot) version, but it's [also having installer issues](https://github.com/kyleneideck/BackgroundMusic/actions).

**Comment by mverrilli** [comment]
Hi @kyleneideck 

I'm getting the same issue on -pre.  I ran with verbose/debug: 

```
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=xxxxxx USER=xxxxxx USERNAME=xxxxxx /usr/sbin/installer -pkg /opt/homebrew/Caskroom/background-music-pre/0.4.0-SNAPSHOT-b38f6dd/BackgroundMusic-0.4.0-SNAPSHOT-b38f6dd.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Background Music 0.4.0-SNAPSHOT-b38f6dd
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Background Music 0.4.0-SNAPSHOT-b38f6dd…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%2.229250
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “BackgroundMusic-0.4.0-SNAPSHOT-b38f6dd.pkg”.)
/opt/homebrew/Library/Homebrew/system_command.rb:302:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:65:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:68:in `block in run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:74:in `with_choices_file'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:61:in `run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:36:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:246:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:239:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:117:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:77:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:77:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:179:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by 0ctopirate** [comment]
This may be an issue with Monterrey?

**Comment by mverrilli** [comment]
Using the pkg installer I was able to get most of it installed. It appears the issue has something to do with installing the helper. The log didn't have much information that's useful, only that a script returned a non-zero result. I am using Monterey 12.3.1.

**Comment by nobeh** [comment]
Having the same issue as @mverrilli with similar logs on Monterey 12.4.

**Comment by aleks-m** [comment]
On Monterey 12.4:

```
2022-06-02 13:23:53+02 stone installd[5417]: PackageKit: Extracting file:///usr/local/Caskroom/background-music-pre/0.4.0-SNAPSHOT-b38f6dd/BackgroundMusic-0.4.0-SNAPSHOT-b38f6dd.pkg#Installer.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/500C01F5-C91A-49B5-A3B3-F25F6B322514.activeSandbox/Root, uid=0)
2022-06-02 13:23:53+02 stone installd[5417]: PackageKit: prevent user idle system sleep
2022-06-02 13:23:53+02 stone installd[5417]: PackageKit: suspending backupd
2022-06-02 13:23:53+02 stone installd[5417]: PackageKit (package_script_service): Preparing to execute script "./preinstall" in /private/tmp/PKInstallSandbox.CpTEjs/Scripts/com.bearisdriving.BGM.vX1fwp
2022-06-02 13:23:53+02 stone package_script_service[35084]: PackageKit: Executing script "preinstall" in /tmp/PKInstallSandbox.CpTEjs/Scripts/com.bearisdriving.BGM.vX1fwp2022-06-02 13:23:53+02 stone package_script_service[35084]: Set responsibility to pid: 1393, responsible_path: /Applications/iTerm.app/Contents/MacOS/iTerm2
2022-06-02 13:23:53+02 stone install_monitor[37400]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2022-06-02 13:23:53+02 stone package_script_service[35084]: ./preinstall: safe_install_dir.sh: line 74: python: command not found
2022-06-02 13:23:53+02 stone package_script_service[35084]: ./preinstall:  is not a directory.
```

```
>python
-bash: python: command not found
```
From https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python:
```
Python 2.7 was removed from macOS in this update. Developers should use Python 3 or an alternative language instead. (39795874)
```

**Comment by Sh1ken** [comment]
Same here with Monterrey 12.4

**Comment by kyleneideck** [comment]
The Python 2 issue should be fixed now in https://github.com/kyleneideck/BackgroundMusic/releases/download/v0.4.0/BackgroundMusic-0.4.0.pkg thanks to #593.

Homebrew won't have v0.4.0 yet, but installing it with the .pkg shouldn't cause any issues with Homebrew. Homebrew might just reinstall it later, I think.

@ErichthoniusX I'm pretty sure the installer failed for you for a different reason, since you were using macOS 11.2.1 and they didn't remove Python 2 until 12.3, but could you try v0.4.0 anyway? Let me know if it still fails for you and I'll reopen the issue.

**Comment by ch60234** [comment]
Ventura 13.3.1 
show this error while installnation
`[1/3] Installing the virtual audio device Background Music Device.driver to /Library/Audio/Plug-Ins/HAL
ERROR: Install failed at line 233 with the message:
A build command failed. Probably a compilation error.

Feel free to report this. If you do, you'll probably want to include the build_and_install.log file from this directory (/var/folders/93/bs54p8bx13b1cl1h54x8r5yw0000gn/T/tmp.3sM2XRsi/BackgroundMusic-master). But quickly skim through it first to check that it doesn't include any personal information. It shouldn't, but this is alpha software so you never know.

To try building and installing without this build script, see MANUAL-INSTALL.md.

You can also try ignoring compiler warnings with: BackgroundMusic-master/build_and_install.sh -w

Error details:
Line 233. The last command was (probably)
    /bin/bash BackgroundMusic-master/build_and_install.sh -w
which exited with status 65.`
