### ISSUE TITLE
Cannot set pan to -1

### ISSUE THREAD

**Issue by marcuswu** [kyleneideck/BackgroundMusic#459]
## Cannot set pan to -1

**Description of the bug**
> Pan values range from -100 to 100, but the value used as a non-value is -1 which means pan can't actually be set to -1. This is a small issue as it's probably not a noticeable difference from 0 or -2, but it'd be nice to address it.

**Steps to reproduce**
> Setting directly to -1 would not change the pan and sliding the slider would never be able to actually reach a -1 value. This is probably only directly testable through code.

**Versions**
> Current trunk

**Debug logs**
> If you think the developers might not be able to reproduce the bug on their computers, e.g. because an important feature is completely broken and they would have noticed, it can help to include [debug logs](https://github.com/kyleneideck/BackgroundMusic/wiki/Getting-Debug-Logs). This takes a little effort, so feel free to leave it out at first.

[Debug logs attached here](https://github.com/example/background-music-debug-logs.txt)

**Other info**
> The related code is in
> * `BGMApp/BGMApp/BGMAppVolumesController.mm`,
> * `setVolumeAndPan:forApp:` in `BGMAppVolumes.m`
> * `getVolumeAndPanForApp:` in `BGMAppVolumes.m`
> * `setVolumeOfMenuItem` in `BGMAppVolumes.m`
> * `setVolumeAndPan:forApp:` in `BGMAppVolumesController.m`
> * `getVolumeAndPanForApp:fromVolumes:` in `BGMAppVolumesController.m`
> * `setVolume:` in `BGMASApplication.m`
> There may be some others as well

**Comment by marcuswu** [comment]
Would we just want to use -101 as a non-value? The other option is to use nullable values for when the desire is to only set one of pan or volume. Thoughts?

**Comment by kyleneideck** [comment]
Yeah, -101 would be fine. Or `INT_MIN`. Maybe adding `#define kAppPanNoValue        INT_MIN` here would be a nice way to do it: https://github.com/kyleneideck/BackgroundMusic/blob/master/SharedSource/BGM_Types.h#L165

Also happy to change the type to be nullable/optional if you'd prefer. I think that's technically the best way, but I probably wouldn't bother just out of laziness.

>Setting directly to -1 would not change the pan and sliding the slider would never be able to actually reach a -1 value. This is probably only directly testable through code.

You can reproduce it with this AppleScript. It will leave Music.app panned all the way to the left, but if you change `-1` to `0`, it will change it back to the center.

```
tell application "Background Music"
	set pan of (a reference to (the first audio application whose name is equal to "Music")) to -100
	set pan of (a reference to (the first audio application whose name is equal to "Music")) to -1
end tell
```
