### ISSUE TITLE
App volumes don't work with Astro A50 Headset

### ISSUE THREAD

**Issue by GuilhermeDSantos** [kyleneideck/BackgroundMusic#462]
It doesn't work with my headset, Astro A50. I think its because it has it's own volume mixer... But in other hand others mixers work, such as Volume Mixer.
![image](https://user-images.githubusercontent.com/53098377/112829421-7d1cc200-9067-11eb-9a52-0f2f3b8ac605.png)

**Comment by kyleneideck** [comment]
I'm assuming you just mean the volume mixer doesn't work for you. Or have you tried the auto-pause feature as well?

What apps have you tried to change the volume of?

**Comment by kyleneideck** [comment]
Also, which version are you using?

**Comment by GuilhermeDSantos** [comment]
> Also, which version are you using?

![image](https://user-images.githubusercontent.com/53098377/112831011-b3f3d780-9069-11eb-87cb-cd96b165d1cb.png)

**Comment by GuilhermeDSantos** [comment]
> I'm assuming you just mean the volume mixer doesn't work for you. Or have you tried the auto-pause feature as well?
> 
> What apps have you tried to change the volume of?

Yes, it does not work for me. I tried all apps that were opened at the time and it didn't work in any.

**Comment by kyleneideck** [comment]
Try this snapshot version: https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-c0ab98b

It's a fair bit newer, so it's worth trying just to see if it changes anything. If that doesn't fix it, can you check that the "Background Music" device gets set as your default audio device when you run Background Music?

**Comment by GuilhermeDSantos** [comment]
> Try this snapshot version: https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-c0ab98b
> 
> It's a fair bit newer, so it's worth trying just to see if it changes anything. If that doesn't fix it, can you check that the "Background Music" device gets set as your default audio device when you run Background Music?

It worked for me, thank you!

**Comment by GuilhermeDSantos** [comment]
> Try this snapshot version: https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-c0ab98b
> 
> It's a fair bit newer, so it's worth trying just to see if it changes anything. If that doesn't fix it, can you check that the "Background Music" device gets set as your default audio device when you run Background Music?

It worked for me, thank you!
