### ISSUE TITLE
brew uninstall

### ISSUE THREAD

**Issue by Lyon52222** [kyleneideck/BackgroundMusic#471]
> There's no template for this issue type. I just wanted to make it clear that it's OK to submit other types of issues.
I installed it with brew and uninstall it with uninstall.sh as you suggested ,but background-music is still in my brew list. How can I remove it from my brew list??

**Comment by kyleneideck** [comment]
The Homebrew formulae aren't managed in this repo. It looks like they're at

 - https://github.com/Homebrew/formulae.brew.sh/blob/master/cask/background-music.html
 - https://github.com/Homebrew/formulae.brew.sh/blob/master/_data/cask/background-music.json
 - https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/background-music-pre.rb
