### ISSUE TITLE
Not able to control sound for Microsoft Edge

### ISSUE THREAD

**Issue by BossElijah** [kyleneideck/BackgroundMusic#474]
**This app works overall, but for this one application (Microsoft Edge) that I use quite a lot, I can't control anything.**

**Steps to reproduce**
1. Go to the BackGround Music app
2. Try the volume slider for Microsoft Edge
3. Nothing happens

**Versions**
 - Background Music: version 0.3.2
 - macOS: "Catalina".

Does anyone know if there is a workaround for this? I've tried to look in 'other apps' to see if there would be some "Microsoft Edge Helper" Application, but it doesn't seem there is one.

**Comment by kyleneideck** [comment]
You might need to add it to https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMApp/BGMBackgroundMusicDevice.cpp#L204 and build from source.

**Comment by BossElijah** [comment]
> You might need to add it to https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMApp/BGMBackgroundMusicDevice.cpp#L204 and build from source.

I'm sorry, I have no idea how to do that.

**Comment by leafney** [comment]
The same issues are encountered.

**Comment by billza7** [comment]
Same issues encountered here. At least can you give instructions on what to add?

**Comment by kyleneideck** [comment]
@billza7 Sure, I've written it up in a wiki article: https://github.com/kyleneideck/BackgroundMusic/wiki/App-Volumes-Fixes

Feel free to edit it or ask questions.
