### ISSUE TITLE
BM crash using zoom

### ISSUE THREAD

**Issue by b3z** [kyleneideck/BackgroundMusic#478]
So if I use bm to regulate my zoom output it works fine for a while. Then bm just seems to crash and my audio is gone. Also the bm tray icon disappears and the task is not in the taskmanager anymore.

To reproduce just use bm with zoom.

**Versions**
big sur 11.2.3 (20D91)
bm 0.3.2

**Hardware**
Pro (13 Zoll, 2020, 4 TB3)
Audio Device HyperX cloud 2 (USB) / Internal speakers

**Comment by kyleneideck** [comment]
Can you try it with the [latest snapshot build](https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-b38f6dd)? I didn't think 0.3.2 worked on Big Sur at all. (I've been meaning to make a new non-snapshot build to avoid this, but I haven't found the time yet.)

**Comment by b3z** [comment]
I am gonna try it today. Actually you are stating a good point there. Still tho 0.3.2 worked for a while on big sur.

**Comment by b3z** [comment]
Seems to work better with the snapshot. :))
