### ISSUE TITLE
Individual volume on window focus.

### ISSUE THREAD

**Issue by b3z** [kyleneideck/BackgroundMusic#482]
It would be nice if you could set yourself two keyboard shortcuts which change the volume of the window in focus.
Any thoughts?

**Comment by kyleneideck** [comment]
Good idea. We've had a few suggestions for global hotkeys before, so I think it would get some use. Let me know if you're interesting in making a PR.

**Comment by b3z** [comment]
I will have a look though I don't know any swift. Still it would be dope because you wouldn't always have to use the mouse and the sliders and also pick the right window in the list.

**Comment by b3z** [comment]
I will not do anything here as of for now. That is why I am closing this.
