### ISSUE TITLE
how to disable auto-pause feature entirely

### ISSUE THREAD

**Issue by pseidemann** [kyleneideck/BackgroundMusic#483]
thanks for this cool tool!

I want to use background music only for controlling volume of apps and recording the system audio.

how can I disable the auto-pause feature entirely? inside the menu, clicking on a player were the checkmark is, does nothing.

thanks!

**Comment by kyleneideck** [comment]
In the main menu, click "Auto-pause [the name of some music player app]" so the checkmark disappears. It's at the top of the menu. It doesn't matter what the music player app is; if that menu item is unchecked, auto-pause will be completely disabled.

I'll admit that the UI is pretty confusing in this respect.

**Comment by aaubin649** [comment]
For some reason, when I do this, it still pauses by itself for no particular reason
