### ISSUE TITLE
Uninstalled BackgroundMusic and it's still showing up in my sound settings

### ISSUE THREAD

**Issue by tanmaik** [kyleneideck/BackgroundMusic#499]
## Example bug report template

**Description of the bug**
Background Music is continuing to show up as an output device even after uninstalling the entire software from my device. MBP 13" 2020 w/ Intel i7

**Steps to reproduce**
> Steps to reproduce the bug. This usually doesn't need to be super detailed.
1. Uninstall the app :)

**Comment by kyleneideck** [comment]
How did you uninstall? You need to use `uninstall.sh`. If that doesn't work, try https://github.com/kyleneideck/BackgroundMusic/blob/master/MANUAL-UNINSTALL.md

**Comment by sergio-opslevel** [comment]
I had the follow [MANUAL-UNINSTALL.md](https://github.com/kyleneideck/BackgroundMusic/blob/master/MANUAL-UNINSTALL.md) and then it was gone completely.

**Comment by jurejuvuify** [comment]
You can find help here: https://github.com/kyleneideck/BackgroundMusic/blob/master/MANUAL-UNINSTALL.md

**Comment by sergio-opslevel** [comment]
To be clear, this issue still exists. Uninstall doesn't work. The above links are simply workarounds.

**Comment by kyleneideck** [comment]
Thanks, @sergio-opslevel. Can you explain how to reproduce the bug? Did you run `uninstall.sh`? Did it give you any error messages or did it just fail silently?
