### ISSUE TITLE
Build fails (El Capitan 10.11.3)

### ISSUE THREAD

**Issue by iammarkoradak** [kyleneideck/BackgroundMusic#52]
This is the output:

```
About to install Background Music. Please pause all audio, if you can.

This script will install:
 - /Applications/Background Music.app
 - /Library/Audio/Plug-Ins/HAL/Background Music Device.driver
 - /Library/Application Support/Background Music/BGMXPCHelper.xpc
 - /Library/LaunchDaemons/com.bearisdriving.BGM.XPCHelper.plist

Continue (y/N)? y
Password:
build_and_install.sh: line 261: wait: pid 1018 is not a child of this shell
Looking for Xcode...
It looks like you have Xcode installed to
/Applications/Xcode.app
imac:BackgroundMusic markoradak$
```

**Comment by kyleneideck** [comment]
Thanks for the heads up. I've just pushed 3f62b01, which I think will probably fix this. Can you try again and let me know if it's worked?

**Comment by iammarkoradak** [comment]
Yep, that fixed it. However, I didn't realize it's not compatible with Boom (I've now saw an issue on that), which is kind of a deal breaker for me. On that note - adding a system wide equalizer would definitely be a game-changer.

Nonetheless, it's an amazing little app. Hope it gets even better :)

**Comment by kyleneideck** [comment]
Cool, thanks. I'll definitely look into adding an equalizer when I get a chance. Should be pretty straightforward.
