### ISSUE TITLE
The "Background Music" option in the menu bar, in the sound icon at the top right of the screen does not disappear once Background Music is removed from the Mac.

### ISSUE THREAD

**Issue by ToniGamezZ** [kyleneideck/BackgroundMusic#526]
That's it basically; The "Background Music" option in the menu bar, in the sound icon at the top right of the screen, does not disappear once Background Music is removed from the Mac. Nor does it disappear from the "Sound" section in System Preferences. 

How can I remove this permanently from my Mac?

I leave some pictures of what I'm talking about attached to this post.

Thank you very much for your support.

<img width="337" alt="Captura de pantalla 2021-08-24 a las 13 39 44" src="https://user-images.githubusercontent.com/83927326/130706675-b97d4d81-16b9-4fe4-9baa-45dfa9024513.png">

<img width="810" alt="Captura de pantalla 2021-08-25 a las 2 21 05" src="https://user-images.githubusercontent.com/83927326/130706710-d6527907-1ced-442e-995e-b8f2973000a9.png">

**Comment by kyleneideck** [comment]
The uninstall instructions are here: https://github.com/kyleneideck/BackgroundMusic#uninstall

There's no way for us to automatically remove the `Background Music` device when you delete `Background Music.app`, unfortunately. I think the best we can do would be to add an "Uninstall" option to the menu in the app, but no one has gotten around to it yet.

Let me know if you still can't get it to uninstall and I'll reopen this ticket.
