### ISSUE TITLE
Won't open on Big Sur 11.0.1 M1 Macbook Pro

### ISSUE THREAD

**Issue by walker44501** [kyleneideck/BackgroundMusic#529]
Background Music won't open on big sur. When I click it, it does the expanding visuals but it doesn't show up, not in toolbar, and not in system preferences. I tried 3.2 and the snap shots that others say work on big sur with no luck. One reason I think might be the cause is I had to manually extract the file from the .pkg using terminal, due to my device being school laptop don't I don't admin rights. 
To replicate just extract the file from terminal and try to open after dragging onto desktop.
Thanks

**Comment by kyleneideck** [comment]
Sorry, but I'm pretty sure it's not possible to install Background Music without an admin account. You need an admin account to install an audio driver, presumably because all users share those drivers, and Background Music doesn't work without its driver installed.
