### ISSUE TITLE
Cannot control volume of iOS/iPadOS app on M1 Mac

### ISSUE THREAD

**Issue by calvarez** [kyleneideck/BackgroundMusic#546]
## Example bug report template

> Don't worry if you have trouble getting some of this info. Just leave it out.

Not sure if this is truly a bug, or it's not expected to work.  I'm running the Overcast iPad app on my M1 Mac, and wanted to control its volume as it doesn't have a built in control.  But BackgroundMusic does nothing.  You can move the slider for Overcast but nothing changes.  It does work on other apps like Apple Music.

**Versions**
> Please complete the following information.
 - Background Music: 0.4.0-SNAPSHOT-b38f6dd
 - macOS: 11.6

**Hardware**
> Delete this part if you think it's probably not necessary.
 - Computer: Mac Mini M1
 - Audio Device: Built in headphone output

**Comment by OlfanK** [comment]
I just downloaded Overcast, subscribed to a random podcast and started playing, also on an M1 Mac Mini.
Its volume controls fine, and I'm using the same snapshot of BackgroundMusic as you. I am on macOS 12.0.1, but that shouldn't (?) matter.

Have you made sure that the audio device chain is set up correctly? BackgroundMusic acts as a virtual sound device. You must set BackgroundMusic as your active sound output device in Apple->System Preferences->Sound->Output, and choose the Mac mini headphone port as "Output Device" in BackgroundMusic's menu. If you play directly through the headphone port, you will not hear what BackgroundMusic does.

**Comment by calvarez** [comment]
I did check, change, and re-change the audio chain, with no effect.  But oddly, after upgrading to 12.0.1, it's working perfectly.  So this was probably just some issue specific to my machine.  Also notable...  Overcast was open when I installed this app, and Overcast crashed during the install.
