### ISSUE TITLE
Security Issue in BGM App UItest

### ISSUE THREAD

**Issue by cack195** [kyleneideck/BackgroundMusic#587]
[xml.etree.ElementTree.parse]() is considered insecure. Use an analog from the defusedxml package.

https://github.com/cack195/BackgroundMusic/blob/baefa8f993a662f4650ccf1792e473992cf9da93/BGMApp/BGMAppTests/UITests/travis-skip.py#L41

It's just a minor issue 
Just want to share

**Comment by kyleneideck** [comment]
Thanks, but the XML file it parses is from our own repo. `ElementTree.parse` is only insecure if you use it to parse untrusted XML.

Let me know if you think I'm missing something and I'll reopen.

**Comment by cack195** [comment]
Hi 
You are right, and I have misunderstood it. 
Thanks, it was a learning for me.

>
