### ISSUE TITLE
Unable to remove background music tab on mac 

### ISSUE THREAD

**Issue by Hedrey** [kyleneideck/BackgroundMusic#607]
Hello ive been having this issue for a while, its nothing too serous just kinda annoying. Im on a mac book pro and when i deleted Background music the tab where you switch audio on mac just stayed there and i have no idea how to remove it

 Picture if you dont understand what i mean - https://user-images.githubusercontent.com/72213937/175960943-94cab53c-d305-4e7d-89e6-ded1528080a4.png

**Comment by kyleneideck** [comment]
I think this should help: <https://github.com/kyleneideck/BackgroundMusic/issues/606#issuecomment-1163941471>. Let me know if that doesn't fix it for you and I'll reopen this issue.
