### ISSUE TITLE
Inquiry about Microsoft Team

### ISSUE THREAD

**Issue by huangkenicole** [kyleneideck/BackgroundMusic#617]
Hello, when I use brew to install this app, everything is ok. 
But I notice when I run the desktop app called "Microsoft Teams", I found when the meeting is meeting, I didn't open the camera and mic, and when others were speaking, **I was unable to control the volume level through the slider of the software**. Thank you for your reply!
![image](https://user-images.githubusercontent.com/104063962/183840227-2261ebf6-9087-4014-a05a-9bd90b2f2cc1.png)

**Comment by jzuijlek** [comment]
Please look for **Microsoft Teams H...** under **More Apps**.

Maybe this can me fixed in an upcoming release.

**Comment by huangkenicole** [comment]
ok, I got it, thanks
