### ISSUE TITLE
Does not autostart when reboot in el capitan 10.11.5

### ISSUE THREAD

**Issue by darkbrow** [kyleneideck/BackgroundMusic#65]
About a month ago, BackgroundMusic installed and worked properly.
A few days ago, I changed my macbook to new one and install BGM via terminal.
Installed and worked well, but when I restart the computer the .app doesn't start automatically.
So I had to launch app manually every restart.

**Comment by kyleneideck** [comment]
I've been meaning to fix that for a while. I think we should be able to just add

```shell
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Background Music.app", hidden:false, name:"Background Music"}'
```

to `build_and_install.sh` and add a "✓ Start at log in" item to the preferences menu in BGMApp.

You're probably already aware of this, but for now you can either run the command above or [add a login item for BGMApp manually](https://support.apple.com/kb/PH18881).

**Comment by darkbrow** [comment]
I manually added app to login item.
Your osascript works like a charm, much better than manual adding.
Thank you.
