### ISSUE TITLE
Discord doesn't work 0.4

### ISSUE THREAD

**Issue by bateman201** [kyleneideck/BackgroundMusic#673]
I've tried almost every previous issue's solution include the owner's mention, nothing works.

The only thing that seems to be affected by the "Discord" slider are the UI sounds

Also, I don't see Discord Helper under "More Apps" as it was mentioned in other posts

Versions

Please complete the following information.
Background Music v0.4
macOS Ventura 13.3.1
Discord v0.0.274

Hardware

MacBook Pro (14-inch, 2023)
Audio Default: Background Music
Background Music Output Option: Macbook Pro speakers

**Comment by jziggas** [comment]
I seem to be experiencing the same thing.

macOS 12.5.1
Discord 0.0.275
Background Music v0.4
Input Device: Background Music
Output Device: Background Music

When this is selected:
Input Device: Background Music
Output Device: Macbook Speakers

The sounds from people talking is choppy and jumbled.

**Comment by FabianMontoya** [comment]
I'm having the same experience. Also, I don't know if it could be related to Opera too. When I change the volume from Opera, all the sounds remain the same.
