### ISSUE TITLE
The mechanism behind background music

### ISSUE THREAD

**Issue by chunyang-wen** [kyleneideck/BackgroundMusic#689]
BackgroundMusic has an awesome feature which is: it can control the volume of each app.

I am just curious how it achieves this. (It is a pity that I am not familiar with the objective-c, I will do my best to learn it).  I have found code in [BGMBackgroundMusicDevice.cpp](https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMApp/BGMBackgroundMusicDevice.cpp) to set and get app volume.

It seems that there is no high level api(or in swift) which we can achieve similar functions. Maybe I am not careful enough to find all the references and resources.

There are paid apps, such as
- [Sound Source](https://rogueamoeba.com/soundsource/)
- [Sound bunny](https://www.prosofteng.com/soundbunny-mac-volume-control)

They can also control the volume of an app. But they require to install a system extension or something similar. **BackgroundMusic does not**. It is awesome.

So anyone can help me understand how background music achieve this. That would be much appreciated. Docs, links or books are also fine.

Thanks very much in advance.

Some reference:
 - https://github.com/kyleneideck/BackgroundMusic/wiki/App-Volumes-Fixes
 - https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMApp/BGMBackgroundMusicDevice.cpp

**Comment by kyleneideck** [comment]
Have a look at https://github.com/kyleneideck/BackgroundMusic/blob/master/DEVELOPING.md.
