### ISSUE TITLE
Background Music not shown in System Settings

### ISSUE THREAD

**Issue by Ecauchy** [kyleneideck/BackgroundMusic#713]
**Description of the bug**
>  I use brew to install the app and it tells me "needs permission to use microphones", meanwhile I cannot find the setting for it in  System Preferences > Security and Privacy > Microphone. There's no box for Background Music.
> Besides when I tried to uninstall it, I follow the manual in the README.md which says that I should execute the uninstall.sh in the app content, but after I execute it, I still cannot install it again using brew. It turns out to be that I should use "brew unintall background-music", am I right?
<img width="715" alt="image" src="https://github.com/kyleneideck/BackgroundMusic/assets/7821408/79813bc7-4c5f-4ddd-b1fc-9b8469afdfc5">

**Steps to reproduce**
> Steps to reproduce the bug. This usually doesn't need to be super detailed.
1. Install the app by "brew install --cask background-music"
2. Click on "System Preferences > Security and Privacy > Microphone"
3. Nothing happened. No check box for Background Music.

**Versions**
> Please complete the following information.
 - Background Music: 0.4.0
 - MacOS: 14.2.1 (23C71)

**Hardware**
> Delete this part if you think it's probably not necessary.
 - Computer: MacBook Pro (13-inch, 2022, M2)
 - Audio Device:  
<img width="905" alt="image" src="https://github.com/kyleneideck/BackgroundMusic/assets/7821408/74a94b66-45b9-4fd1-bc97-3c54fd7f6eeb">

**Comment by Ecauchy** [comment]
It turns out to be a problem connected with the apple system but not bgm. I delete ~/Library/Preferences/com.apple.systempreferences.plist and restart my mac, and open bgm and then everything is OK.

**Comment by dandingdjianjiao** [comment]
> It turns out to be a problem connected with the apple system but not bgm. I delete ~/Library/Preferences/com.apple.systempreferences.plist and restart my mac, and open bgm and then everything is OK.

I tried this, still not working.
