### ISSUE TITLE
after quit bgm, the chrome audio can not output

### ISSUE THREAD

**Issue by habaohaba** [kyleneideck/BackgroundMusic#733]
**Description of the bug**
after quit bgm, the chrome audio can not output

**Steps to reproduce**
open bgm
open chrome and open a youtube video
quit bgm
chrome audio can not output

**Versions**
 - Background Music: 0.4.3
 - macOS: 14.4.1 (23E224)

**Hardware**
macbook pro m2 pro
built in speaker

**Comment by kyleneideck** [comment]
It's only happening with Chrome? What's your default output device set to after you quit Background Music?

Background Music sets the default output device back to your real device (from the Background Music virtual device) when you quit it. If that's working and Chrome is ignoring the default device setting, that would be a bug in Chrome, but that seems unlikely to me.

**Comment by habaohaba** [comment]
I reinstall BGM and the problem solved, will publish more info if problem happen again. Thank you.
