### ISSUE TITLE
"Mic Mode" only, w/ no preferences, etc

### ISSUE THREAD

**Issue by TXCiclista** [kyleneideck/BackgroundMusic#745]
Running the most recent version downloaded from this page. I have only "Mic Mode" as an option (Standard and Voice Isolation as choices), and see a message "Wide Spectrum is not available." There are not preferences I can access. Right-clicking the Menu bar icon does nothing. I am running Sonoma 14.4.1 on an M1 Max Mac Studio. BGM is set as the output device under Sound.

EDIT: As of 14.6.1, BGM is working as expected. Not sure what changed, but issue has resolved itself somehow

**Comment by howtomacyt** [comment]
same problem here.

**Comment by jelove** [comment]
I believe this is a non-issue, there are too many icons taking up the space. Close a few of them (for instance I had multiple VLC icons in the tray) and it will show up. I don't know if there's a way to show the hidden icons or scroll through them, alas.

**Comment by TXCiclista** [comment]
No, that’s not the issue. Icon displays just fine.

**Comment by mocenigo** [comment]
Are you on macOS 15.x beta?

**Comment by TXCiclista** [comment]
No, per my original post, 14.4.1 (now 14.5, with no change)

**Comment by howtomacyt** [comment]
> I believe this is a non-issue, there are too many icons taking up the space. Close a few of them (for instance I had multiple VLC icons in the tray) and it will show up. I don't know if there's a way to show the hidden icons or scroll through them, alas.

This worked for me. Too many icons in menubar. Cleared it up and background music icon appeared. thanks!

**Comment by TXCiclista** [comment]
> > I believe this is a non-issue, there are too many icons taking up the space. Close a few of them (for instance I had multiple VLC icons in the tray) and it will show up. I don't know if there's a way to show the hidden icons or scroll through them, alas.
> 
> This worked for me. Too many icons in menubar. Cleared it up and background music icon appeared. thanks!

Why are these two comments here? This is unrelated to the issue I reported.

**Comment by howtomacyt** [comment]
> > > I believe this is a non-issue, there are too many icons taking up the space. Close a few of them (for instance I had multiple VLC icons in the tray) and it will show up. I don't know if there's a way to show the hidden icons or scroll through them, alas.
> > 
> > 
> > This worked for me. Too many icons in menubar. Cleared it up and background music icon appeared. thanks!
> 
> Why are these two comments here? This is unrelated to the issue I reported.

Because I had the same problem. I'm pretty sure. I'm sorry if you have a different problem, however jelove's comment was the solution to the exact problem I had. 
Since you mentioned only seeing the Mic icon, I suppose I had the same problem.
I would still try and remove icons from your menu bar, you should see the mic icon AS WELL AS the backgroundmusic app icon, and if you click on it you should see preferences.

**Comment by TXCiclista** [comment]
I see the BGM icon. It’s that in the opp icon and n the menu bar, the only options listed are “Mic Mode.” No icons are listed for any apps. It’s not an issue of not being able to see the app itself, but of the app not functioning properly.

**Comment by TXCiclista** [comment]
Updated OP, but 14.6.1 appears to have corrected the issue. Wasn't functioning properly as of 14.6. Updated yesterday, went to check today and all seems well. Closing the ticket.
