### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by limsammy** [kyleneideck/BackgroundMusic#78]
>Sams-MacBook-Pro:~ sam$ (set -eo pipefail; URL='https://github.com/kyleneideck/BackgroundMusic/archive/master.tar.gz';     cd $(mktemp -d); echo Downloading $URL to $(pwd); curl -qfL# $URL | gzcat - | tar x &&     /bin/bash BackgroundMusic-master/build_and_install.sh && rm -rf BackgroundMusic-master)
Downloading https://github.com/kyleneideck/BackgroundMusic/archive/master.tar.gz to /var/folders/kd/m0kfb4bd0zvb8zsnd83nqnbr0000gn/T/tmp.NI8ozlav
######################################################################## 100.0%
About to install Background Music. Please pause all audio, if you can.

>This script will install:
 - /Applications/Background Music.app
 - /Library/Audio/Plug-Ins/HAL/Background Music Device.driver
 - /usr/local/libexec/BGMXPCHelper.xpc
 - /Library/LaunchDaemons/com.bearisdriving.BGM.XPCHelper.plist

>Continue (y/N)? y
[1/3] Installing the virtual audio device Background Music Device.driver to /Library/Audio/Plug-Ins/HAL.
ERROR: Install failed at line 196 with the message:

>A build command failed. Probably a compilation error.

>Failed command:
                            sudo /usr/bin/xcodebuild -project BGMDriver/BGMDriver.xcodeproj -target Background Music Device -configuration Release RUN_CLANG_STATIC_ANALYZER=0 DSTROOT=/ clean install

>Feel free to report this. If you do, you'll probably want to include the build_and_install.log file from this directory (/var/folders/kd/m0kfb4bd0zvb8zsnd83nqnbr0000gn/T/tmp.NI8ozlav/BackgroundMusic-master). But quickly skim through it first to check that it doesn't include any personal information. It shouldn't, but this is alpha software so you never know.

>To try building and installing without this build script, see MANUAL-INSTALL.md.

Not sure what to do.

**Comment by kyleneideck** [comment]
Thanks for reporting this. Did the install script leave a build_and_install.log file in `/var/folders/kd/m0kfb4bd0zvb8zsnd83nqnbr0000gn/T/tmp.NI8ozlav`? If it did, can you paste it into this issue?

**Comment by rlewkowicz** [comment]
@limsammy 
This is just a guess, but you may need to accept your xcode build license:
sudo xcodebuild -license accept

**Comment by limsammy** [comment]
Yep, that worked! New laptop, hadn't even opened Xcode yet.

**Comment by kyleneideck** [comment]
Nice guess. Thanks, @rlewkowicz. I've added a check to the build script so it can fail with a useful error message when the Xcode license needs to be accepted.
