### ISSUE TITLE
Can I uninstall Xcode after installing Background music ?

### ISSUE THREAD

**Issue by manojfedx** [kyleneideck/BackgroundMusic#80]
Hi Im new here! I don't know shit about coding or whatever! One of my friends suggested your blog !
When I saw this I was disappointed as I have to install Xcode to run this! SO now if I'm going to install Xcode and then BMusic and then again uninstall Xcode. Will my Bm work now??
Thanks in advance!

**Comment by kyleneideck** [comment]
Yeah, you just need Xcode to install Background Music. You can uninstall it afterwards.
