### ISSUE TITLE
Doesn't work for VMWare Fusion

### ISSUE THREAD

**Issue by p33t3r** [kyleneideck/BackgroundMusic#86]
I realize that this might not be an issue that affects many people, and that Fusion is quite expensive to buy and test for, but in my case my job as a subtitler requires me to work exclusively in Windows, and I do that through Fusion.
For some reason audio through Fusion is rather quiet, and it would be very nice to be able to use BGM to raise the volume level.
Again, I understand if this is not a pressing issue. I will be happy to provide any logs or other documentation you may need.

**Comment by nosekefik** [comment]
In don't works on Parallels too

**Comment by kyleneideck** [comment]
Should be fixed for VMWare Fusion and Parallels Desktop now. Thanks for reporting it.
